### ISSUE TITLE
can't override variables that are already defined in remote .bashrs

### ISSUE THREAD

**Issue by ezbik** [fsquillace/kyrat#22]
Hi, it is impossible to redefine variables that already exist on remote side e.g. HISTFILESIZE.
My local kyrat bashrc has `HISTFILESIZE=50000`
Remote bashrc has `HISTFILESIE=2000` (ubuntu default)
Now, `/tmp/kyrat-znP5K/bashrc` is extended with the line `source /root/.bashrc` so remote bashrc takes precedence.
So in remote session HISTFILESIZE is stil 2000

**Comment by ezbik** [comment]
lib/core.sh:162
```
        [[ -e \${HOME}/.bashrc ]] && echo \"source \${HOME}/.bashrc\" >> \"\${kyrat_home}/bashrc\";
```

can be moved from the bottom to the top I believe?

**Comment by fsquillace** [comment]
Good point.

The solution is to prepend `source ${HOME}/.bashrc` inside the file `${kyrat_home}/bashrc`. One solution is to use `sed` but I would like to reduce the number of dependencies. I will investigate more...

**Comment by fsquillace** [comment]
https://www.cyberciti.biz/faq/bash-prepend-text-lines-to-file/

**Comment by fsquillace** [comment]
Oh I see your point. It was easier than I thought. I think we can actually put that line in the top.

**Comment by fsquillace** [comment]
Pushed into master branch.

Thanks @ezbik !!
