### ISSUE TITLE
zsh support

### ISSUE THREAD

**Issue by ya2s** [fsquillace/kyrat#32]
Is there any support for zsh so that zshrc can be used instead of bashrc?

**Comment by fsquillace** [comment]
Thanks for the feedback. I think that's possible! I have a solution working I'll need to make some tests and should be ready soon.

Will keep you updated.

**Comment by fsquillace** [comment]
https://github.com/fsquillace/kyrat/pull/34

**Comment by fsquillace** [comment]
Change merged into master. Thanks again! Closing.
