### ISSUE TITLE
Way to kyrat and run a (passed along) bash function

### ISSUE THREAD

**Issue by csm10495** [fsquillace/kyrat#38]
Hey folks,

If I kyrat to a host, can I somehow run a function that was passed along in the bashrc file?

Say i have:
```
function hello() {
    echo "hello"
}
```
in my bashrc that kyrat passed along.

I can't seem to just run:

```
kyrat HOST hello
```

Is there a way to be able to do that?

**Comment by csm10495** [comment]
Ah i think i found a way to do it:

```
kyrat  HOST  <<<  FUNCTION
```

**Comment by fsquillace** [comment]
Try this:

```
kyrat HOST -- hello
```

Resolving.
